# Generated by Django 2.2.2 on 2019-06-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Cliente',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=60)),
                ('nacionalidade', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=14)),
            ],
            options={
                'db_table': 'TB_Cliente',
            },
        ),
    ]
