# Generated by Django 2.2.2 on 2019-06-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_cliente',
            old_name='nacionalidade',
            new_name='email',
        ),
    ]
